name: PR Checks

on:
  pull_request:

jobs:
  pr-checks:
    name: Run Flutter Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set Up Java
      #   uses: actions/setup-java@v3.12.0
      #   with:
      #     distribution: 'oracle'
      #     java-version: '17'
  
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'          

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project
        run: flutter clean

    # TODO Uncomment the following lines to enable full_coverage
    #   - name: Activate full_coverage
    #     run: dart pub global activate full_coverage

    #   - name: Run full_coverage
    #     run: dart pub global run full_coverage
        
    #   - name: Run fix_full_coverage_file script
    #     run: dart run scripts/dart/fix_full_coverage_file.dart
        
    #   - name: Run tests
    #     run: flutter test ./test

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Check for suggested fixes
        run: dart fix --dry-run

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      # TODO Uncomment the following lines to enable dart_code_metrics  

      # - name: Install DCM
      #   uses: CQLabs/setup-dcm@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Executar DCM
      #   run: dcm analyze --ci-key="${{ secrets.DCM_CI_KEY }}" --email="${{ secrets.DCM_EMAIL }}" lib
